spring.application.name=demo
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5433/start
spring.datasource.username=bro
spring.datasource.password=lina
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
